export default async function getDomesticSum() {
  const initialData = {
    Province: {
      Bangkok: 0,
      Phuket: 0,
      Nonthaburi: 0,
      Chonburi: 0,
      "Samut Prakan": 0,
      Yala: 0,
      Songkhla: 0,
      Pattani: 0,
      Narathiwat: 0,
      "Chiang Mai": 0,
      "Pathum Thani": 0,
      "Nakhon Pathom": 0,
      Chumphon: 0,
      Chachoengsao: 0,
      Krabi: 0,
      "Nakhon Ratchasima": 0,
      Satun: 0,
      "Surat Thani": 0,
      "Prachuap Khiri Khan": 0,
      "Ubon Ratchathani": 0,
      Phatthalung: 0,
      "Samut Sakhon": 0,
      Buriram: 0,
      "Nakhon Si Thammarat": 0,
      "Udon Thani": 0,
      "Sa Kaeo": 0,
      Surin: 0,
      Kanchanaburi: 0,
      "Nakhon Sawan": 0,
      Prachinburi: 0,
      "Chiang Rai": 0,
      Sisaket: 0,
      Trang: 0,
      Ratchaburi: 0,
      "Suphan Buri": 0,
      Rayong: 0,
      Phitsanulok: 0,
      "Khon Kaen": 0,
      "Mae Hong Son": 0,
      Saraburi: 0,
      Loei: 0,
      "Phra Nakhon Si Ayutthaya": 0,
      Lampang: 0,
      Lamphun: 0,
      Mukdahan: 0,
      Phetchabun: 0,
      Phayao: 0,
      Sukhothai: 0,
      Tak: 0,
      "Nong Bua Lamphu": 0,
      Chanthaburi: 0,
      "Roi Et": 0,
      Uttaradit: 0,
      Kalasin: 0,
      Chaiyaphum: 0,
      "Nong Khai": 0,
      Phetchaburi: 0,
      "Nakhon Phanom": 0,
      "Phang Nga": 0,
      Lopburi: 0,
      "Amnat Charoen": 0,
      "Nakhon Nayok": 0,
      Phrae: 0,
      "Uthai Thani": 0,
      Yasothon: 0,
      "Sakon Nakhon": 0,
      "Samut Songkhram": 0,
      "Maha Sarakham": 0,
    },
    Nation: {
      Unknown: 3119,
      Burmese: 56,
      Swiss: 6,
      Kazakhstani: 2,
      Spain: 2,
      British: 1,
    },
    Gender: { Male: 1758, Female: 1428 },
    LastData: "2020-07-04 00:00:00",
    UpdateDate: "04/07/2020",
    Source: "https://data.go.th/dataset/covid-19-daily",
    DevBy: "https://www.kidkarnmai.com/",
    SeverBy: "https://smilehost.asia/",
  };

  try {
    const res = await fetch("https://covid19.th-stat.com/api/open/cases/sum");
    return await res.json();
  } catch (error) {
    return initialData;
  }
  //

  // return await res.json();
}
